import type { DepthRoomAssets } from '../components/DepthRoomCanvas';
import type { DepthRoomOverrideConfig } from './roomDefinitions';
import type { RoomSceneId } from './roomManifest';

/**
 * Depth-renderer assets per room, generated by scripts/build-depth-rooms.sh:
 * one stable painting, one decayed painting, one grayscale depth map
 * (white = near), and a lamp-glow layer. `windowRect` marks the padded
 * painting region (UV, v-up) where the willow feed video shows through the
 * painting's transparent glass. Rooms absent from this map fall back to the
 * legacy layer-plate renderer.
 */
const DEPTH_ROOM_ASSETS: Partial<Record<RoomSceneId, DepthRoomAssets>> = {
  lab: {
    stableUrl: '/rooms/observation/depth/stable.png',
    decayedUrl: '/rooms/observation/depth/decayed.png',
    depthUrl: '/rooms/observation/depth/depth.png',
    glowUrl: '/rooms/observation/depth/glow.jpg',
    windowRect: { minX: 0.2427, minY: 0.463, maxX: 0.6777, maxY: 0.932 },
  },
  'break-room': {
    stableUrl: '/rooms/break-room/depth/stable.png',
    decayedUrl: '/rooms/break-room/depth/decayed.png',
    depthUrl: '/rooms/break-room/depth/depth.png',
    glowUrl: '/rooms/break-room/depth/glow.jpg',
    // TV screen on the back wall
    windowRect: { minX: 0.548, minY: 0.808, maxX: 0.662, maxY: 0.932 },
  },
  'signal-cartography': {
    stableUrl: '/rooms/signal-cartography/depth/stable.png',
    decayedUrl: '/rooms/signal-cartography/depth/decayed.png',
    depthUrl: '/rooms/signal-cartography/depth/depth.png',
    glowUrl: '/rooms/signal-cartography/depth/glow.jpg',
  },
};

export const getDepthRoomAssets = (roomId: RoomSceneId): DepthRoomAssets | null =>
  DEPTH_ROOM_ASSETS[roomId] ?? null;

/**
 * Merge admin overrides (config/rooms -> depth) over the built-in assets.
 * Returns null when the renderer is disabled or the required textures
 * (stable, decayed, depth map) cannot be assembled.
 */
export const resolveDepthRoomAssets = (
  roomId: RoomSceneId,
  override?: DepthRoomOverrideConfig | null,
): DepthRoomAssets | null => {
  const base = DEPTH_ROOM_ASSETS[roomId] ?? null;
  if (!override) return base;
  if (override.enabled === false) return null;

  const stableUrl = override.stableUrl ?? base?.stableUrl;
  const decayedUrl = override.decayedUrl ?? base?.decayedUrl;
  const depthUrl = override.depthUrl ?? base?.depthUrl;
  if (!stableUrl || !decayedUrl || !depthUrl) return null;

  return {
    stableUrl,
    decayedUrl,
    depthUrl,
    glowUrl: override.glowUrl ?? base?.glowUrl,
    windowRect: override.windowRect === null
      ? undefined
      : override.windowRect ?? base?.windowRect,
  };
};
